// Build the playground into docs/playground/ (deploys to GitHub Pages alongside
// the landing page). Bundles the app + the SHARED portable kernel (compiler,
// themes, lint, types) + mediabunny + gifenc into one ESM file via esbuild.
//
// Also generates playground/src/scenes-data.ts from showcase/scenes.ts so the
// playground's example list and the gallery's deep-link targets are the SAME
// scene definitions — one source of truth, no drift.

import { build } from "esbuild"
import { mkdir, writeFile, copyFile, readdir } from "node:fs/promises"
import { resolve, dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { SHOWCASE } from "../showcase/scenes.js"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, "..")
const OUT = join(ROOT, "docs", "playground")
const SRC = join(__dirname, "src")

// the starter scene shown on first load (mirrors src/init.ts EXAMPLE)
const STARTER = {
  meta: { aspect: "wide", theme: { preset: "claude" }, window: { chrome: "mac", title: "demo" } },
  steps: [
    { cmd: "npm install termscene" },
    { out: "added 1 package in 1.2s", style: "dim" },
    { cmd: "termscene render demo.scene.json --out demo.gif" },
    { out: "wrote demo.gif", style: "ok" },
  ],
}

async function genScenesData() {
  // a compact index for the gallery swatches + the playground example chips
  const index = SHOWCASE.map((s) => ({
    id: s.id,
    name: s.name,
    blurb: s.blurb,
    sw: (s.scene.meta?.theme && THEME_SW[s.scene.meta.theme.preset as string]) || "#d97757",
    scene: s.scene,
  }))
  const body = `// AUTO-GENERATED by playground/build.ts from showcase/scenes.ts — do not edit.
// One source of truth: the gallery deep-links and the playground examples share these.
import type { Scene } from "../../src/types.js"

export const STARTER = ${JSON.stringify(JSON.stringify(STARTER, null, 2))}

export interface ShowcaseIndexEntry {
  id: string
  name: string
  blurb: string
  sw: string
  scene: Scene
}

export const SHOWCASE_INDEX: ShowcaseIndexEntry[] = ${JSON.stringify(index, null, 2)}
`
  await writeFile(join(SRC, "scenes-data.ts"), body)
}

// swatch colors per preset (match the gallery in docs/index.html)
const THEME_SW: Record<string, string> = {
  claude: "#d97757",
  gemini: "#a78bfa",
  codex: "#10a37f",
  warp: "#4c8dff",
  iterm2: "#00d7af",
  macos: "#cfcfcf",
  ubuntu: "#8ae234",
  starship: "#88c0d0",
  midnight: "#58a6ff",
  matrix: "#37d837",
  paper: "#a8442a",
}

async function main() {
  await mkdir(OUT, { recursive: true })
  await mkdir(join(OUT, "fonts"), { recursive: true })

  // 1. generate the shared scenes data
  await genScenesData()

  // 2. copy fonts (same JBM woff2 the engine uses)
  const fontsSrc = join(ROOT, "src", "engine", "fonts")
  for (const f of await readdir(fontsSrc)) {
    if (f.endsWith(".woff2")) await copyFile(join(fontsSrc, f), join(OUT, "fonts", f))
  }

  // 3. copy the static html
  await copyFile(join(__dirname, "index.html"), join(OUT, "index.html"))

  // 4. bundle the app
  const result = await build({
    entryPoints: [join(SRC, "main.ts")],
    bundle: true,
    format: "esm",
    target: "es2022",
    outfile: join(OUT, "playground.js"),
    minify: true,
    // sourcemap on only when DEBUG=1 — the committed/deployed bundle ships without
    // a 1.2MB .map (and no dangling sourceMappingURL 404 on the published site).
    sourcemap: process.env.DEBUG === "1",
    logLevel: "info",
    metafile: true,
  })
  const out = result.metafile?.outputs[join("docs", "playground", "playground.js").replace(/\\/g, "/")]
  if (out) console.log(`bundle: ${(out.bytes / 1024).toFixed(0)} KB`)
  console.log(`playground → ${OUT}`)
}

main().catch((e) => {
  console.error("playground build error:", e)
  process.exit(1)
})
